apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DATABASE_USER: postgres # Base64-encoded 'postgres' Change it with real value
  DATABASE_PASSWORD: postgres # Base64-encoded 'postgres' Change it with real value
