apiVersion: v1
kind: Service
metadata:
  name: konfio-enterprise-query-service-service
spec:
  selector:
    app: konfio-enterprise-query-service
  ports:
    - protocol: TCP
      port: 80          # External access port
      targetPort: 3000  # App's container port
  type: LoadBalancer   # Exposes the service to the internet
